In [1]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
69 * np.ones((2,3))

array([[69., 69., 69.],
       [69., 69., 69.]])

In [4]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random()

0.8402783941004596

In [6]:
np.random.random((2,3))

array([[0.30975993, 0.56279189, 0.33461782],
       [0.95998358, 0.66205297, 0.47894585]])

# Standard normal distribution (Gaussian) where mean = 0 and variance = 1 -> "random.randn()"

In [7]:
np.random.randn(2,3)

array([[-0.32836476,  0.28113607, -1.70146528],
       [ 0.74728305, -0.41161231, -1.61423222]])

In [8]:
R = np.random.randn(10000)

In [9]:
R.mean()

0.0037153479108813043

In [10]:
np.mean(R)

0.0037153479108813043

In [11]:
R.var()

1.0129351862496228

In [12]:
 R.std()

1.0064468124295605

In [13]:
R = np.random.randn(10000, 3)

In [14]:
R.mean(axis=0)

array([-0.01346786, -0.00548101, -0.00901068])

In [15]:
R.mean(axis=1).shape

(10000,)

In [16]:
np.cov(R)

array([[ 1.90742077, -0.37344801, -1.54750235, ..., -1.75020034,
         2.33774005,  1.20833343],
       [-0.37344801,  0.14368563,  0.145597  , ...,  0.55801538,
        -0.16813916,  0.01322172],
       [-1.54750235,  0.145597  ,  1.60649503, ...,  0.93967748,
        -2.54239844, -1.53742637],
       ...,
       [-1.75020034,  0.55801538,  0.93967748, ...,  2.26309662,
        -1.2614319 , -0.34645523],
       [ 2.33774005, -0.16813916, -2.54239844, ..., -1.2614319 ,
         4.05325937,  2.50590389],
       [ 1.20833343,  0.01322172, -1.53742637, ..., -0.34645523,
         2.50590389,  1.64968744]])

In [17]:
np.cov(R).shape

(10000, 10000)

In [18]:
np.cov(R.T)

array([[ 1.02778772e+00,  3.90568269e-04, -7.24585276e-04],
       [ 3.90568269e-04,  9.98689030e-01,  4.03703455e-03],
       [-7.24585276e-04,  4.03703455e-03,  1.03507873e+00]])

In [19]:
np.cov(R, rowvar=False)

array([[ 1.02778772e+00,  3.90568269e-04, -7.24585276e-04],
       [ 3.90568269e-04,  9.98689030e-01,  4.03703455e-03],
       [-7.24585276e-04,  4.03703455e-03,  1.03507873e+00]])

In [21]:
np.random.randint(0, 100, size=(3,3))

array([[95, 95, 89],
       [48,  2, 16],
       [64, 22, 43]])

In [22]:
np.random.choice(10, size=(3,3))

array([[8, 2, 4],
       [6, 3, 6],
       [8, 2, 2]])