In [1]:
import numpy as np

In [2]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [3]:
L[0]

[1, 2]

In [4]:
L[0][1]

2

In [7]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
A[0,1]

2

In [9]:
A.T

array([[1, 3],
       [2, 4]])

In [10]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [11]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [12]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [14]:
 A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [15]:
A.T.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
B.T.dot(A)

array([[13, 18],
       [17, 24],
       [21, 30]])

In [17]:
np.linalg.det(A)

-2.0000000000000004

In [20]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [21]:
A.dot(A_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [22]:
A_inv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [23]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [24]:
np.trace(A)

5

In [25]:
np.diag(A)

array([1, 4])

In [26]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])